### PR TITLE
Add favicon. Closes #112

### LINKED ISSUE #112: Add favicon
Here's is how it looks currently:

Chrome
image

Firefox 
image

Assigning this to myself.

### PR DESCRIPTION
**Pull request by anymoto**
Here's how it looks now:

In orange (Chrome):
image

In white (Chrome):
image

[My branch staging](https://railsbridge-staging.herokuapp.com/)

### CODE REVIEW

**Comment by tjgrathwell** [comment]
Is there a way to do a version that is just the red icon but on a transparent background?

**Comment by anymoto** [comment]
Yes! I'm on it

**Comment by anymoto** [comment]
@tjgrathwell done :+1: 

image

**Comment by tjgrathwell** [comment]
:star2: :smile_cat: :star2:

it is deployed :rocket:

**Comment by lilliealbert** [comment]
YAY! Great catch, @anymoto!!!

**Pull request merged**
