### PR TITLE
Replace School Foundry references with Bridge Foundry

### PR DESCRIPTION
**Pull request by mxie**
Bridge Foundry is now its own 501(c)(3), separate from School Factory. As an official Bridge of the organization, we need to update any old references and donations buttons to be representative of Bridge Foundry instead.

### CODE REVIEW

**Comment by dianaluepke** [comment]
The wording changes look great to me! I can't tell if this will update the graphic as well?

**Comment by mxie** [comment]
@dianaluepke I don't think the graph actually changes. It's just the underlying code that it uses to take the viewer to the right place.

**Comment by dianaluepke** [comment]
@mxie I'm not 100% sure I understand your reply. Do you mean that the photo just needs to be edited and re-uploaded, the code pointing to it doesn't need to change? If so, that makes sense. (To make sure we're on the same page, this is what I'm referring to: https://github.com/railsbridge/railsbridge_dot_org/blob/master/app/assets/images/railsbridge-structure.png )

**Comment by mxie** [comment]
@dianaluepke Oh! I didn't even know about the graphic! I'll have to see what I can do there...might have to create a new one. Unless you've got one handy? :D

**Comment by dianaluepke** [comment]
Well it is slightly less confusing now, so you could consider just taking it out for now? I know there's a long term goal to develop something the Bridge websites can query and have an up to date graphic or list of Bridges/Chapters/Communities... but we don't have anything that's exactly right currently. You could link to this, but it's not from RailsBridge's perspective. https://docs.google.com/presentation/d/1H4KhqUaalIGJM5VAxDIMBQAZlDu3_Xdj5HSupFpNxL4/edit?usp=sharing

**Comment by dianaluepke** [comment]
@mxie P.S. this is the page it shows on. http://railsbridge.org/about/team

**Comment by mxie** [comment]
@dianaluepke Got it - thank you! I've removed the image for now.

**Pull request merged**
