### PR TITLE
Update about.html.haml

### PR DESCRIPTION
**Pull request by FerPerales**
* Fix a typo

### CODE REVIEW

**Comment by ultrasaurus** [comment]
thanks @FerPerales for the PR!

This typo fix definitely does not seems like something that would break the build!  Appreciate your alerting us in Slack.  Investigating what's up with CI

**Comment by ultrasaurus** [comment]
well, trying out [autorebase bot](https://github.com/tibdex/autorebase) didn't work... CI is fixed now, but this branch needs to be updated (manually, I guess) before merging

**Comment by FerPerales** [comment]
@ultrasaurus branch updated

**Pull request merged**
